version: '2'
services:
  # Notice how the service name, container name and repo directory (where the Dockerfile lives) all match.
  lender-ui-a:
    container_name: lender-ui-a
    build: ./lender-ui
    environment:
      APP_USER: 'loans4homes'
      LENDER_MANAGEMENT_API_URL: 'http://lender-management-api-a:8080/v1'
      LENDER_API_URL: 'http://host.docker.internal:7020/api'
    restart: on-failure
    ports:
      # The base Flask Dockerfile tells gunicorn to use 8080 by default, we expose it here and map it to a unique
      # port for the app (which is subsequently used by the dev-env to forward it outside of vagrant too).
      - "7009:8080"
    volumes:
      # Our convention is (for python) to always map the app files to /src within the container
      - ./lender-ui:/src
    # Redirect all the logs to a logstash server. Logstash is set up to parse RFC5424 format messages.
    logging:
      driver: syslog
      options:
        syslog-format: "rfc5424"
        syslog-address: "tcp://localhost:25826"
        tag: "{{.Name}}"
    # Docker-compose will ensure logstash is started before the application starts.
    depends_on:
      - logstash
  lender-ui-b:
    container_name: lender-ui-b
    build: ./lender-ui
    environment:
      APP_USER: "gringott's bank"
      LENDER_MANAGEMENT_API_URL: 'http://lender-management-api-b:8080/v1'
      LENDER_API_URL: 'http://host.docker.internal:7021/api'
    restart: on-failure
    ports:
      # The base Flask Dockerfile tells gunicorn to use 8080 by default, we expose it here and map it to a unique
      # port for the app (which is subsequently used by the dev-env to forward it outside of vagrant too).
      - "7010:8080"
    volumes:
      # Our convention is (for python) to always map the app files to /src within the container
      - ./lender-ui:/src
    # Redirect all the logs to a logstash server. Logstash is set up to parse RFC5424 format messages.
    logging:
      driver: syslog
      options:
        syslog-format: "rfc5424"
        syslog-address: "tcp://localhost:25826"
        tag: "{{.Name}}"
    # Docker-compose will ensure logstash is started before the application starts.
    depends_on:
      - logstash
